# model params
backbone_type: resnet_v2_m_50
loss_type: arcface
out_type: E

image_size: 112
embd_size: 512
# class_num: 85742   # original
class_num: 5000        # Bernardo


# hyper params
bn_decay: 0.9
keep_prob: 0.4

weight_decay: !!float 5e-4      # original
# weight_decay: !!float 5e-1        # Bernardo

logits_scale: 64.0   # original
# logits_scale: 32.0     # Bernardo

logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: True

# augment_flag: True   # original
augment_flag: False    # Bernardo

augment_margin: 16


gpu_num: 1

# batch_size: 100    # original
batch_size: 64     # Bernardo


# epoch_num: 30
epoch_num: 150

# step_per_epoch: 100000   # original
step_per_epoch: 1000        # Bernardo

val_freq: 2000

lr_steps: [5000, 10000, 15000]

# lr_values: [0.004, 0.002, 0.0012, 0.0004]            # original
# lr_values: [0.04, 0.02, 0.012, 0.004]                # Bernardo
# lr_values: [0.05, 0.01, 0.005, 0.001]                # Bernardo
# lr_values: [0.1, 0.05, 0.01, 0.001]                  # Bernardo
lr_values: [0.01, 0.005, 0.0025, 0.001]              # Bernardo


# paths
# pretrained_model: '/data/hhd/InsightFace-tensorflow/output/20190120-133421/checkpoints/ckpt-m-140000'      # original
pretrained_model: ''                                                                                         # Bernardo

# train_data: ['/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface.tfrecord']                  # original
train_data: ['/experiments/bjgbiesseck/datasets/MS-Celeb-1M/ms1m-retinaface-t1/images_5000subj.tfrecord']     # Bernardo

# val_data: {'agedb_30': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/agedb_30.bin', 'lfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/lfw.bin', 'cfp_ff': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cfp_ff.bin', 'cfp_fp': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cfp_fp.bin', 'calfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/calfw.bin', 'cplfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cplfw.bin', 'vgg2_fp': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/vgg2_fp.bin'}
val_data: {'agedb_30': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/agedb_30.bin', 'lfw': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/lfw.bin', 'cfp_ff': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/cfp_ff.bin', 'cfp_fp': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/cfp_fp.bin', 'calfw': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/calfw.bin', 'cplfw': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/cplfw.bin', 'vgg2_fp': '/experiments/bjgbiesseck/datasets/MS-Celeb-1M/faces_emore/vgg2_fp.bin'}

output_dir: './output'

