# model params
backbone_type: resnet_v2_m_50
loss_type: arcface
out_type: E

image_size: 112
embd_size: 512
# class_num: 85742   # original
class_num: 22        # Bernardo


# hyper params
bn_decay: 0.9
keep_prob: 0.4

weight_decay: !!float 5e-4      # original
# weight_decay: !!float 5e-1        # Bernardo

logits_scale: 64.0   # original
# logits_scale: 32.0     # Bernardo

logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: True

# augment_flag: True   # original
augment_flag: False    # Bernardo

augment_margin: 16


gpu_num: 1

# batch_size: 100   # original
batch_size: 64      # Bernardo

# epoch_num: 20     # original
epoch_num: 5        # Bernardo

# step_per_epoch: 100000   # original
step_per_epoch: 100        # Bernardo

val_freq: 100

lr_steps: [40000, 60000, 80000]

lr_values: [0.004, 0.002, 0.0012, 0.0004]                   # original
# lr_values: [0.01, 0.2, 0.12, 0.4]                         # Bernardo


# paths
# pretrained_model: '/data/hhd/InsightFace-tensorflow/output/20190120-133421/checkpoints/ckpt-m-140000'      # original
pretrained_model: ''                                                                                         # Bernardo

# train_data: ['/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface.tfrecord']                               # original
# train_data: ['/datasets1/bjgbiesseck/MS-Celeb-1M/ms1m-retinaface-t1/images_reduced.tfrecord']                    # duo (Bernardo)
train_data: ['/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/ms1m-retinaface-t1/images_reduced.tfrecord']   # diolkos (Bernardo)

# val_data: {'agedb_30': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/agedb_30.bin', 'lfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/lfw.bin', 'cfp_ff': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cfp_ff.bin', 'cfp_fp': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cfp_fp.bin', 'calfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/calfw.bin', 'cplfw': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/cplfw.bin', 'vgg2_fp': '/data/hhd/dataset/FaceData/InsightFace/faces_ms1m_arcface/vgg2_fp.bin'}
# val_data: {'agedb_30': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/agedb_30.bin', 'lfw': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/lfw.bin', 'cfp_ff': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/cfp_ff.bin', 'cfp_fp': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/cfp_fp.bin', 'calfw': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/calfw.bin', 'cplfw': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/cplfw.bin', 'vgg2_fp': '/datasets1/bjgbiesseck/MS-Celeb-1M/faces_emore/vgg2_fp.bin'}   # duo
val_data: {'agedb_30': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/agedb_30.bin', 'lfw': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/lfw.bin', 'cfp_ff': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/cfp_ff.bin', 'cfp_fp': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/cfp_fp.bin', 'calfw': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/calfw.bin', 'cplfw': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/cplfw.bin', 'vgg2_fp': '/nobackup/unico/datasets/face_recognition/MS-Celeb-1M/faces_emore/vgg2_fp.bin'}   # diolkos


output_dir: './output'

